backend/urls.py
from django.urls import path
from .views import InferenceAPIView, DataInferenceAPIView
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "backend"  

urlpatterns = [
                path('inference/api/', DataInferenceAPIView.as_view(), name="inference-api"),
                path('results/api', InferenceAPIView.as_view(), name="results-api"),
                path('predict/', views.prediction, name="predict")
                 ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dmai/urls.py
from django.contrib import admin
from django.urls import path,include

from backend import urls as backend_urls
from frontend import urls as frontend_urls
from testbot import urls as testbot_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('endpoints/', include(backend_urls)),
    path('testbot/', include(testbot_urls)),
    path('', include(frontend_urls))
]

frontend/urls.py
from django.urls import path
from .views import FrontendAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "frontend"  

urlpatterns = [
                path('', FrontendAPIView.index, name = 'index'),
                # path('home/api/', FrontendAPIView.as_view(), name="home-api")
                ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

testbot/urls.py
from django.urls import path
from .views import TestbotAPIView
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = "testbot"  

urlpatterns = [
                path('', TestbotAPIView.testbot, name = 'testbot'),
                path('letschat/', views.convo, name = 'letschat'),
                path('testbot/api/', TestbotAPIView.as_view(), name="testbot-api")
                ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

class Frontend(models.Model):
    pass

testbot/models.py
from django.db import models

# Create your models here.

class Testbot(models.Model):
    text_id = models.AutoField(primary_key=True)
    is_bot = models.IntegerField()
    text = models.CharField(max_length=200,null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

class CollectData(models.Model):
    text_id = models.AutoField(primary_key=True)
    is_bot = models.IntegerField()
    text = models.CharField(max_length=200,null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

testbot/forms.py
from django import forms


class TestbotForm(forms.Form):
    input_field = forms.CharField(max_length=255, widget=(forms.TextInput(attrs={'class':'form-control','placeholder':'Type a here...', 'class':'textarea'})))

frontend/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Frontend
from .serializers import FrontendModelSerializer
from backend.forms import DataForm
# Create your views here.

class FrontendAPIView(APIView):

    def get(self, request):
        frontend = Frontend.objects.all()
        serializer = FrontendModelSerializer(frontend, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = FrontendModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)

    def index(request):
        data_form = DataForm()
        return render(request, template_name='pages/index.html', context={'data_form':data_form})

testbot/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Testbot
from .serializers import TestbotModelSerializer
from .forms import TestbotForm
import numpy as np
import random
import json
from .models import Testbot, CollectData
from django.utils import timezone
import nltk
import torch
import torch.nn as nn
nltk.download('punkt')
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
# Create your views here.

MODELS_PATH = './models/'

class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.l1 = nn.Linear(input_size, hidden_size) 
        self.l2 = nn.Linear(hidden_size, hidden_size) 
        self.l3 = nn.Linear(hidden_size, num_classes)
        self.relu = nn.ReLU()
    
    def forward(self, x):
        out = self.l1(x)
        out = self.relu(out)
        out = self.l2(out)
        out = self.relu(out)
        out = self.l3(out)
        # no activation and no softmax at the end
        return out

class TestbotAPIView(APIView):

    def get(self, request):
        testbot = Testbot.objects.all()
        serializer = TestbotModelSerializer(testbot, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = TestbotModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)

    def testbot(request):
        Testbot.objects.all().delete()
        testbot_form = TestbotForm()
        return render(request, template_name='pages/testbot.html', context={'testbot_form':testbot_form})


def bag_of_words(tokenized_sentence, words):
    # stem each word
    sentence_words = [stemmer.stem(str(word).lower()) for word in tokenized_sentence]
    # initialize bag with 0 for each word
    bag = np.zeros(len(words), dtype=np.float32)
    for idx, w in enumerate(words):
        if w in sentence_words: 
            bag[idx] = 1

    return bag    


def convo(request):

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    with open(MODELS_PATH+'testbot.json', 'r') as json_data:
        intents = json.load(json_data)

    FILE = MODELS_PATH+"model_data.pth"
    data = torch.load(FILE,map_location=device)

    input_size = data["input_size"]
    hidden_size = data["hidden_size"]
    output_size = data["output_size"]
    all_words = data['all_words']
    tags = data['tags']
    model_state = data["model_state"]

    model = NeuralNet(input_size, hidden_size, output_size).to(device)
    model.load_state_dict(model_state)
    model.eval()

    if request.method == 'POST':

            testbot_form = TestbotForm(request.POST)

            if testbot_form.is_valid():

                sentence = request.POST['input_field']

                new_chat = Testbot(is_bot=0, text=sentence)
                new_chat.save()
                new_chat_data = CollectData(is_bot=0, text=sentence)
                new_chat_data.save()

                sentence_token = nltk.word_tokenize(sentence)
                X = bag_of_words(sentence_token, all_words)
                X = X.reshape(1, X.shape[0])
                X = torch.from_numpy(X).to(device)

                output = model(X)
                _, predicted = torch.max(output, dim=1)

                tag = tags[predicted.item()]

                # bot_response = None
                probs = torch.softmax(output, dim=1)
                prob = probs[0][predicted.item()]
                if prob.item() > 0.75:
                    for intent in intents['intents']:
                        if tag == intent["tag"]:
                            bot_response = random.choice(intent['response'])
                            new_chat = Testbot(is_bot=1, text=bot_response)
                            new_chat.save()
                            new_chat_data = CollectData(is_bot=1, text=bot_response)
                            new_chat_data.save()
                            chats = Testbot.objects.all()
                            testbot_form = TestbotForm()
                            return render(request, template_name='pages/testbot.html', context={'testbot_form':testbot_form,'chats':chats})
                else:
                    bot_response = 'I do not understand...'
                    new_chat = Testbot(is_bot=1, text=bot_response)
                    new_chat.save()
                    new_chat_data = CollectData(is_bot=1, text=bot_response)
                    new_chat_data.save()
                    chats = Testbot.objects.all()
                    testbot_form = TestbotForm()
                    return render(request, template_name='pages/testbot.html', context={'testbot_form':testbot_form,'chats':chats})

            else:
                 print(testbot_form.errors.as_data()) # here you print errors to terminal
    Testbot.objects.all().delete()
    testbot_form = TestbotForm()
    return render(request, template_name='pages/testbot.html', context={'testbot_form':testbot_form})

frontend/templates/pages/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Home</title>
	<link rel="stylesheet" type="text/css" href="{% static 'frameworks/bootstrap/dist/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'frameworks/bootstrap/dist/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'frameworks/front-awesome/css/front-awesome.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container-fluid">

<main>
 <div class="row" style="margin-top:200px">
 	<div class="col-md-10 col-md-offset-1 col-sm-12">
 		<div class="panel  panel-primary" >
            <div class="panel-heading">
                <p class="h3 text-center">NEXT CUSTOMER PURCHASE PREDICTOR</p>
            </div>
        </div>
        <div class="form-group">
           <div class="panel panel-default">
              <div class="panel-heading">
                  <p class="h4 text-center">*upload json, excel, or csv file containing previous purchases.</p>
                  <p class="h5 text-center text-danger">Note: Previous purchases should not be less than 20.</p>
              </div>
               <div class="panel-body">

                   <div class="form-group">

               <form role="form" method="POST" action="{% url 'backend:predict' %}" enctype="multipart/form-data">
                {% csrf_token %}
                   <div class="row">
                       <div class="col-md-6 col-md-offset-1 col-sm-12"><br><br>
                        {{ data_form.filename }}
                           <!-- <input type="file" name="file" class="form-control"> -->
                       </div><br><br>
                       <div class="col-md-4 col-sm-12">
                           <button class="btn btn-primary" type="submit">Predict</button>
                           <a class="btn btn-success" href="{% url 'backend:inference-api' %}">API Endpoints</a>
                           <a class="btn btn-warning" href="{% url 'frontend:index' %}">Reset</a>
                           <a class="btn btn-info" href="{% url 'testbot:testbot' %}">Demo Chatbot</a>
                       </div>
                       <div class="col-md-12 col-sm-12">
                        <hr>
                        {% if format_message %}
                           <p class="text-center text-danger h4">{{ format_message }}</p>
                        {% endif %}
                       </div>
                       <div class="col-md-12">
                        {% if inference_label == 1 %}
                        <hr>
                        <p class="text-center text-success h4">{{ inference_text }}</p>
                        {% endif %}
                        {% if inference_label == 0 %}
                        <hr>
                        <p class="text-center text-warning h4">{{ inference_text }}</p>
                        {% endif %}
                        {% if inference_label == -1 %}
                        <hr>
                        <p class="text-center text-danger h4">Unpredictable</p>
                        {% endif %}
                    </div>
                   </div>
               </form>
               </div>

          </div>
        </div>
 	</div>
 </div>
</main>
</div>
</body>
</html>

frontend/templates/pages/testbot.html
{% load static%}
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'frameworks/bootstrap/dist/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'frameworks/bootstrap/dist/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'frameworks/front-awesome/css/front-awesome.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/cssbot.css' %}">
</head>

<div class="col-md-4 col-md-offset-4 col-sm-12" style="margin-top:150">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <p class="text-center h3">Demo Chatbot</p>
        </div>
        <div class="panel-body" style="height:600; overflow-y: scroll;">
            <div>
                <form method="POST" action="{% url 'testbot:letschat' %}">
                {% csrf_token %}
                {% for c in chats %}
                <ol class="chat">
                    {% if c.is_bot == 1 %}
                      <li class="other">
                            <div class="avatar"><img src="{% static 'images/bot.png'%}" draggable="false"/></div>
                            <div class="msg">
                            <p>{{ c.text }}</p>
                              <time>{{ c.created_at }}</time>
                            </div>
                      </li>
                      {% endif %}
                      {% if c.is_bot == 0 %}
                      <li class="self">
                            <div class="avatar"><img src="{% static 'images/user.png'%}" draggable="false"/></div>
                            <div class="msg">
                            <p>{{ c.text }}</p>
                              <time>{{ c.created_at }}</time>
                            </div>
                      </li>
                      {% endif %}
                </ol>
            {% endfor %}
            <hr>
            <!-- <input class="textarea" type="text" placeholder="Type here!"/> -->
            {{ testbot_form.input_field }}
            <hr>
            <div>
                <a class="btn btn-warning pull-left" href="{% url 'frontend:index' %}">Back to Predictor</a>
                <button class="btn btn-info pull-right"  type="submit">Send</button>
            </div>
            </form>

        </div>
    </div>

</div>



    </html>